project:
  type: website

website:
  title: "DSAN 5600"
  sidebar:
    style: "docked"
    search: true
    contents:
        - introduction.qmd
        - data_sources.qmd
        - data_visualization.qmd
        - exploratory_data_analysis.qmd
        - arma_arima_sarima_models.qmd
        - arimax_sarimax_var.qmd
        - spectral_analysis.qmd
        - financial_time_series_models.qmd
        - deep_learning_for_ts.qmd
        - conclusions.qmd
        - about.qmd

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    fontsize: 1em

editor: visual

