project:
  type: website

website:
  title: "Crime Time Series Analysis"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Introduction"
        contents:
          - introduction.qmd  
          - about.qmd
      - section: "Data"
        contents: 
          - data_sources.qmd
          - data_visualization.qmd
          - exploratory_data_analysis.qmd
      - section: "Methods"
        contents: 
          - arma_arima_sarima_models.qmd
          - arimax_sarimax_var.qmd
          - financial_time_series_models.qmd
          - deep_learning_for_ts.ipynb
          - interrupted_series.qmd
      - conclusions.qmd
          

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    fontsize: 1em

editor: visual

