---
title: "Conclusions"
---

This extensive time series analysis of crime in New York City yielded a variety of conclusions. Some crimes exhibited clear trends while others did not. Here we will go through each section of the project and evaluate some of the most important takeaways from each. 

# Single-Variable Models

The initial, single variable modelling yielded a variety of useful conclusions. The total arrests time series, despite the significant dip due to COVID in the early 2020's and subsequent rise, was forecasted to continue its pre-COVID trend of a slight decrease. Other models are forecasting at a similar rate as the present, showing that we are back to pre-COVID trends there as well. The two most stationary crimes were motor vehicle theft and murder, as their forecasts did not show much change compared to current rates. These crimes seemed to be the ones least affected by COVID. Overall, all models that were fit outperformed our benchmark models, meaning we can effectively model arrest rates in New York City at rates better than the benchmarks we observed. 

# Multi-Variable Models

Adding exogenous variables to our models also yielded interesting conclusions. Unemployment rate did not seem to affect our total arrests forecasts, as forecasting with that as an exogenous variable yielded similar results to the model without it. Unsurprisingly, this was also observed when looking at the relationship between unemployment rate and a specific crime, such as murder arrests. Similar results were seen when using election years as an exogenous variable.

Modelling the relationship between two time series also yielded interesting conclusions. When modelling the relationship between robbery and unemployment rate using a VAR model, we found that robbery was a better predictor of unemployment rate than vice versa. We also fit a model looking at a similar relationship between controlled substance arrests and marijuana arrests. This VAR model showed us that both variables are excellent predictors of each other, suggesting that they are closely related. Statistics concerning arrests for one type of controlled substance can give us great information about statistics concerning all controlled substances. 

# Financial Time Series Models

Our modelling of CoreCivic stock yielded interesting results, particularly in its volatility clustering. As mentioned in that analysis, the volatility of that asset showed unusual patterns, especially in the early 2020's. When many stocks were exhibitng periods of great change due to the global pandemic, CoreCivic was experiencing relatively low volatility compared to the rest of the market. Rather, it had large volatility in the late 2010's. This may show the strength of these assets that are closely related to crime, as they were able to stay consistent even in periods of otherwise high volatility. 

# Deep Learning Models

Our deep learning models did a reasonable job of forecasting, though their performance was not so much better than traditional models that it would warrant a switch, especially considering the higher computing cost. The most interesting conclusion from that analysis was when forecasting the total arrests time series using our GRU model, we could see that the predicted values were much higher than our actual values, something that we did not see when using our traditional models. This may suggest an increase in crime rates in the coming months and years. 

# Interrupted Time Series

The final and, in my opinion, most interesting part of analysis was seen in looking at interrupted time series. Both events that were looked at yielded interesting results. The more obvious case was the change in marijuana laws in New York City. The decriminalization of marijuana led to a decrease in arrests, something that would not have happened were it not for the change in the laws.

A more interesting conclusion, however, was the changes seen in assault and robbery arrests as a result of the changes to the stop-and-frisk laws in 2013. Despite the significant decrease in stops as a result of the stop-and-frisk policy, there was no change in robbery arrests, suggesting that those policies did little to prevent those crimes from happening. The opposite was seen in assault arrests, as after the change to the law was made, assault arrests decreased significantly. Had the changes not been made, assault arrests would have continued to increase. A sustained, long-term change to a decreasing trend suggests that the stop-and-frisk policy was related to increased assaults in New York City, the opposite of the desired effect. 

# Final Thoughts

Overall, we can see that crime in New York City can be accurately forecasted using these models, and valuable information was gained as a result. A natural next step in this analysis would be to apply this work to other large cities, and maybe even smaller cities to see what their data look like. Do all cities have similar data to New York City? Are east coast cities different than west coast cities? What affect does the size of the city have on crime rate? I would also like to expand my intervention analysis to account for more sophisticated models, as right now I am only using linear regression as my predictive model. These steps would result in an excellent improvement upon what is already very informative analysis, and hopefully would provide useful information to those attempting to make important policy decisions on what to do to keep us safe and prosperous.
