---
title: "Crime as a Time Series"
author: "Thomas Sigall"
bibliography: reference.bib
---

# Crime

Time-series data for crime throughout the United States is readily available and the variety of attempts the government has made over the years makes looking at how crime has changed over those years an interesting task.

# Big Picture

Determining which attempts by the government at city, state, and national levels have been successful and which attempts have been unsuccessful is an incredibly important task. Doing this will help the government to make better decisions to not only keep people safe, but also put their citizens in the best position to life prosperous lives, arguably the most important role the government can play.

Understanding the patterns in crimes committed can help keep citizens safe, but it can also help potential criminals find a better path in life. Knowing when we may be due for an increase in certain types of crimes can help us to take proactive, rather than reactive measures to those potential increases. A detailed understanding of crime patters is arguably one of the the most important things a government cam do in keeping its citizens safe and prosperous.

# Literature Review

There have been countless attempts to understand crime over the years, one interesting one being found in the Handbook of Labor Economics titled "The economics of crime" by Richard B. Freeman. He takes an interesting look at crime through an economic lens, describing this attempt as focusing on "...the effect of incentives on criminal behavior, the way decisions interact in a market setting; and the use of a benefit-cost framework to assess alternative strategies to reduce crime [@freeman_chapter_1999]. This is a useful approach when looking at time-series data as economic data is possibly the most widely used application of such data.

This approach can also be seen when analyzing crime alongside the economy, as this can reveal many motivating factors for committing crime. A 2002 paper demonstrated how the declining labor market in the 1980's, for example, coincided with increasing crime rates among young men during the same time period. The opposite trend was observed in the following decade [@gould_crime_2002]. Papers like these help to bridge the gap between the economy and crime and demonstrate how multi-disciplinary the subject truly is.

# Analytical Angles

```{mermaid}
flowchart TD

data(Raw Crime Data) --> crime(Model Crime)
data --> indicators(Model Economic Indicators)
data --> stocks(Model Stocks)

crime --> intervention(Intervention Analysis)
indicators --> intervention
stocks --> intervention

```

The overall process can be seen in the flowchart above and can be understood as follows:

1. Raw crime data will be obtained
2. Various models including those using just the raw crime data, models with economic indicators as exogenous variables, and financial models with related assets will all be fit. 
3. The best and most accurate models from those will be used in an interrupted time series analysis using various events as the interventions to compare the effect those events had on crime rate to determine which events were the most and least successful at impacting those rates. 

# Guiding Questions

1.  How can we use the economy as a means by which to analyze crime data?
2.  What are some metrics we can use to determine the effectiveness of government action?
3.  What are good predictors of crime?
4.  Is it more effective to try and stop crimes before they are commited or to help those who commit crimes after they do so?
5.  What ethical concerns do we need to be aware of if we are attempting to predict what crimes will be committed?
6.  Is action needed the most at the city, state, or federal level?
7.  Does the economy influence crime, does crime influence the economy, or is it a mix of both?
8.  Is it worth looking at other countries to see what works and what doesn't? Or are all countries more or less the same in their relationship with crime?
9.  Which area of crime would be the most effective to attempt reform in?
10. Could we quantify the negative effect different crimes have on society?

# References
